/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_owlplug_host_loaders_jni_JNIPluginMapper */

#ifndef _Included_com_owlplug_host_loaders_jni_JNIPluginMapper
#define _Included_com_owlplug_host_loaders_jni_JNIPluginMapper
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_owlplug_host_loaders_jni_JNIPluginMapper
	* Method:    mapPlugin
	* Signature: (Ljava/lang/String;)Lcom/owlplug/host/NativePlugin;
	*/
	JNIEXPORT jobject JNICALL Java_com_owlplug_host_loaders_jni_JNIPluginMapper_mapPlugin
	(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
