/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_owlplug_host_NativeHostJNI */

#ifndef _Included_com_owlplug_host_NativeHostJNI
#define _Included_com_owlplug_host_NativeHostJNI
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_owlplug_host_NativeHostJNI
	* Method:    loadPlugin
	* Signature: (Ljava/lang/String;)Lcom/owlplug/host/NativePlugin;
	*/
	JNIEXPORT jobject JNICALL Java_com_owlplug_host_NativeHostJNI_loadPlugin
	(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
