/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_owlplug_host_NativeHostJNI */

#ifndef _Included_com_owlplug_host_NativeHostJNI
#define _Included_com_owlplug_host_NativeHostJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_owlplug_host_NativeHostJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_owlplug_host_NativeHostJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
