name: Owlplug Dev

on: 
  push:
    branches:
      - '**'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 27
      uses: actions/setup-java@v6
      with:
        distribution: 'temurin'
        java-version: 27
        cache: 'maven'
    - name: Build maven parent project
      run: mvn -B install -DskipTests
    - name: Run Test
      run: mvn test
